# config/elasticsearch.yml

development: &default
  es_bin: '/usr/share/elasticsearch/bin/elasticsearch'
  host: 'http://localhost:9200'
  port: '9200'
test:
  es_bin: '/usr/share/elasticsearch/bin/elasticsearch'
  host: 'http://localhost:9250'
  port: '9250'
production:
  es_bin: '/usr/share/elasticsearch/bin/elasticsearch'
  host: 'http://localhost:443'
  port: '443'