# config/elasticsearch.yml

development: &default
  es_bin: '/usr/share/elasticsearch/bin/elasticsearch'
  host: 'http://localhost:9200'
  port: '9200'
test:
  es_bin: '/usr/share/elasticsearch/bin/elasticsearch'
  host: 'http://localhost:9250'
  port: '9250'
production:
  host: "<%= ENV['SEARCHBOX_URL'] %>"
  port: '443'